### ISSUE TITLE
Instructions to build from source is missing

### ISSUE THREAD

**Issue by santhoshtr** [RedHatOfficial/RedHatFont#15]
Please provide instructions to build from source and associated scripts(example: Makefile or similar scripts)

**Comment by starryeyez024** [comment]
What are you trying to build?

**Comment by santhoshtr** [comment]
It is very common to build these files from source code for various purposes(Packaging for operating systems, learning purposes, when somebody want to modify and rebuild the font etc etc). Reproducibility is very very important.

**Comment by alexmyczko** [comment]
```
$ cd source_files/Display
$ fontmake -u */*.ufo -o otf
```
seems to do it.

**Comment by alexmyczko** [comment]
> Thanks for this, @alexmyczko
> 
> Here's my process.
> 
> For TTF there are two steps. Build the compiled fonts, and then autohint those files:
> 
> ```
> $ cd source_files/
> $ python build_ttf.py
> $ cd source_files/fonts
> $ python ttfPostProcess.py
> ```
> 
> For OTF there's one step:
> 
> ```
> $ cd source_files/
> $ python build.py
> ```

Would fail for me with:

```
TTX Magic Time
-----------------------
/var/www/debian/fonts-redhat/RedHatFont-2.3.2/source_files/Display/Regular/master_ttf/RedHatDisplay-Regular.ttf
No flat kerning found
Traceback (most recent call last):
  File "build_ttf.py", line 382, in <module>
    main()
  File "build_ttf.py", line 375, in main
    processFont(file, d, flat_kerning)
  File "build_ttf.py", line 183, in processFont
    name = font['name'].getName(6, 1, 0, 0).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by hbjydev** [comment]
What about building the WOFF/WOFF2 files?

**Comment by alexmyczko** [comment]
for woff2 you can just use woff2_compress ?

**Comment by alexmyczko** [comment]
@dmc5179 https://repology.org/project/ttfautohint/versions it's been around for years?
